### ISSUE TITLE
Unable to compile in Arduino IDE 2.0, error 13

### ISSUE THREAD

**Issue by andypiper** [AnaviTechnology/anavi-thermometer-sw#45]
Trying to compile this in Arduino IDE 2.0 is reporting:

```
Compilation error: Error: 13 INTERNAL: exit status 1
```

I set the compilation messages to verbose, and see:

```
Using board 'generic' from platform in folder: /Users/andypiper/Library/Arduino15/packages/esp8266/hardware/esp8266/3.0.2
Using core 'esp8266' from platform in folder: /Users/andypiper/Library/Arduino15/packages/esp8266/hardware/esp8266/3.0.2
Detecting libraries used...
/Users/andypiper/Library/Arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/3.0.4-gcc10.3-1757bed/bin/xtensa-lx106-elf-g++ -D__ets__ -DICACHE_FLASH -U__STRICT_ANSI__ -D_GNU_SOURCE -I/Users/andypiper/Library/Arduino15/packages/esp8266/hardware/esp8266/3.0.2/tools/sdk/include -I/Users/andypiper/Library/Arduino15/packages/esp8266/hardware/esp8266/3.0.2/tools/sdk/lwip2/include -I/Users/andypiper/Library/Arduino15/packages/esp8266/hardware/esp8266/3.0.2/tools/sdk/libc/xtensa-lx106-elf/include -I/private/var/folders/3t/s2qs3f713zvgvt7kq31rkrxc0000gn/T/arduino-sketch-61C39F221C08F1DF8BAEF1771E5B7836/core -c -w -Werror=return-type -Os -g -free -fipa-pta -mlongcalls -mtext-section-literals -fno-rtti -falign-functions=4 -std=gnu++17 -ffunction-sections -fdata-sections -fno-exceptions -DMMU_IRAM_SIZE=0x8000 -DMMU_ICACHE_SIZE=0x8000 -w -x c++ -E -CC -DNONOSDK22x_190703=1 -DF_CPU=80000000L -DLWIP_OPEN_SRC -DTCP_MSS=536 -DLWIP_FEATURES=1 -DLWIP_IPV6=0 -DARDUINO=10607 -DARDUINO_ESP8266_GENERIC -DARDUINO_ARCH_ESP8266 "-DARDUINO_BOARD=\"ESP8266_GENERIC\"" -DLED_BUILTIN=2 -DFLASHMODE_DOUT -DESP8266 -I/Users/andypiper/Library/Arduino15/packages/esp8266/hardware/esp8266/3.0.2/cores/esp8266 -I/Users/andypiper/Library/Arduino15/packages/esp8266/hardware/esp8266/3.0.2/variants/generic /private/var/folders/3t/s2qs3f713zvgvt7kq31rkrxc0000gn/T/arduino-sketch-61C39F221C08F1DF8BAEF1771E5B7836/sketch/anavi-thermometer-sw.ino.cpp -o /dev/null
Alternatives for ESP8266WiFi.h: [ESP8266WiFi@1.0]
ResolveLibrary(ESP8266WiFi.h)
  -> candidates: [ESP8266WiFi@1.0]
/Users/andypiper/Library/Arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/3.0.4-gcc10.3-1757bed/bin/xtensa-lx106-elf-g++ -D__ets__ -DICACHE_FLASH -U__STRICT_ANSI__ -D_GNU_SOURCE -I/Users/andypiper/Library/Arduino15/packages/esp8266/hardware/esp8266/3.0.2/tools/sdk/include -I/Users/andypiper/Library/Arduino15/packages/esp8266/hardware/esp8266/3.0.2/tools/sdk/lwip2/include -I/Users/andypiper/Library/Arduino15/packages/esp8266/hardware/esp8266/3.0.2/tools/sdk/libc/xtensa-lx106-elf/include -I/private/var/folders/3t/s2qs3f713zvgvt7kq31rkrxc0000gn/T/arduino-sketch-61C39F221C08F1DF8BAEF1771E5B7836/core -c -w -Werror=return-type -Os -g -free -fipa-pta -mlongcalls -mtext-section-literals -fno-rtti -falign-functions=4 -std=gnu++17 -ffunction-sections -fdata-sections -fno-exceptions -DMMU_IRAM_SIZE=0x8000 -DMMU_ICACHE_SIZE=0x8000 -w -x c++ -E -CC -DNONOSDK22x_190703=1 -DF_CPU=80000000L -DLWIP_OPEN_SRC -DTCP_MSS=536 -DLWIP_FEATURES=1 -DLWIP_IPV6=0 -DARDUINO=10607 -DARDUINO_ESP8266_GENERIC -DARDUINO_ARCH_ESP8266 "-DARDUINO_BOARD=\"ESP8266_GENERIC\"" -DLED_BUILTIN=2 -DFLASHMODE_DOUT -DESP8266 -I/Users/andypiper/Library/Arduino15/packages/esp8266/hardware/esp8266/3.0.2/cores/esp8266 -I/Users/andypiper/Library/Arduino15/packages/esp8266/hardware/esp8266/3.0.2/variants/generic -I/Users/andypiper/Library/Arduino15/packages/esp8266/hardware/esp8266/3.0.2/libraries/ESP8266WiFi/src /private/var/folders/3t/s2qs3f713zvgvt7kq31rkrxc0000gn/T/arduino-sketch-61C39F221C08F1DF8BAEF1771E5B7836/sketch/anavi-thermometer-sw.ino.cpp -o /dev/null
Alternatives for ESP8266httpUpdate.h: [ESP8266httpUpdate@1.3]
ResolveLibrary(ESP8266httpUpdate.h)
  -> candidates: [ESP8266httpUpdate@1.3]
/Users/andypiper/Library/Arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/3.0.4-gcc10.3-1757bed/bin/xtensa-lx106-elf-g++ -D__ets__ -DICACHE_FLASH -U__STRICT_ANSI__ -D_GNU_SOURCE -I/Users/andypiper/Library/Arduino15/packages/esp8266/hardware/esp8266/3.0.2/tools/sdk/include -I/Users/andypiper/Library/Arduino15/packages/esp8266/hardware/esp8266/3.0.2/tools/sdk/lwip2/include -I/Users/andypiper/Library/Arduino15/packages/esp8266/hardware/esp8266/3.0.2/tools/sdk/libc/xtensa-lx106-elf/include -I/private/var/folders/3t/s2qs3f713zvgvt7kq31rkrxc0000gn/T/arduino-sketch-61C39F221C08F1DF8BAEF1771E5B7836/core -c -w -Werror=return-type -Os -g -free -fipa-pta -mlongcalls -mtext-section-literals -fno-rtti -falign-functions=4 -std=gnu++17 -ffunction-sections -fdata-sections -fno-exceptions -DMMU_IRAM_SIZE=0x8000 -DMMU_ICACHE_SIZE=0x8000 -w -x c++ -E -CC -DNONOSDK22x_190703=1 -DF_CPU=80000000L -DLWIP_OPEN_SRC -DTCP_MSS=536 -DLWIP_FEATURES=1 -DLWIP_IPV6=0 -DARDUINO=10607 -DARDUINO_ESP8266_GENERIC -DARDUINO_ARCH_ESP8266 "-DARDUINO_BOARD=\"ESP8266_GENERIC\"" -DLED_BUILTIN=2 -DFLASHMODE_DOUT -DESP8266 -I/Users/andypiper/Library/Arduino15/packages/esp8266/hardware/esp8266/3.0.2/cores/esp8266 -I/Users/andypiper/Library/Arduino15/packages/esp8266/hardware/esp8266/3.0.2/variants/generic -I/Users/andypiper/Library/Arduino15/packages/esp8266/hardware/esp8266/3.0.2/libraries/ESP8266WiFi/src -I/Users/andypiper/Library/Arduino15/packages/esp8266/hardware/esp8266/3.0.2/libraries/ESP8266httpUpdate/src /private/var/folders/3t/s2qs3f713zvgvt7kq31rkrxc0000gn/T/arduino-sketch-61C39F221C08F1DF8BAEF1771E5B7836/sketch/anavi-thermometer-sw.ino.cpp -o /dev/null
Alternatives for ESP8266HTTPClient.h: [ESP8266HTTPClient@1.2]
ResolveLibrary(ESP8266HTTPClient.h)
  -> candidates: [ESP8266HTTPClient@1.2]
/Users/andypiper/Library/Arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/3.0.4-gcc10.3-1757bed/bin/xtensa-lx106-elf-g++ -D__ets__ -DICACHE_FLASH -U__STRICT_ANSI__ -D_GNU_SOURCE -I/Users/andypiper/Library/Arduino15/packages/esp8266/hardware/esp8266/3.0.2/tools/sdk/include -I/Users/andypiper/Library/Arduino15/packages/esp8266/hardware/esp8266/3.0.2/tools/sdk/lwip2/include -I/Users/andypiper/Library/Arduino15/packages/esp8266/hardware/esp8266/3.0.2/tools/sdk/libc/xtensa-lx106-elf/include -I/private/var/folders/3t/s2qs3f713zvgvt7kq31rkrxc0000gn/T/arduino-sketch-61C39F221C08F1DF8BAEF1771E5B7836/core -c -w -Werror=return-type -Os -g -free -fipa-pta -mlongcalls -mtext-section-literals -fno-rtti -falign-functions=4 -std=gnu++17 -ffunction-sections -fdata-sections -fno-exceptions -DMMU_IRAM_SIZE=0x8000 -DMMU_ICACHE_SIZE=0x8000 -w -x c++ -E -CC -DNONOSDK22x_190703=1 -DF_CPU=80000000L -DLWIP_OPEN_SRC -DTCP_MSS=536 -DLWIP_FEATURES=1 -DLWIP_IPV6=0 -DARDUINO=10607 -DARDUINO_ESP8266_GENERIC -DARDUINO_ARCH_ESP8266 "-DARDUINO_BOARD=\"ESP8266_GENERIC\"" -DLED_BUILTIN=2 -DFLASHMODE_DOUT -DESP8266 -I/Users/andypiper/Library/Arduino15/packages/esp8266/hardware/esp8266/3.0.2/cores/esp8266 -I/Users/andypiper/Library/Arduino15/packages/esp8266/hardware/esp8266/3.0.2/variants/generic -I/Users/andypiper/Library/Arduino15/packages/esp8266/hardware/esp8266/3.0.2/libraries/ESP8266WiFi/src -I/Users/andypiper/Library/Arduino15/packages/esp8266/hardware/esp8266/3.0.2/libraries/ESP8266httpUpdate/src -I/Users/andypiper/Library/Arduino15/packages/esp8266/hardware/esp8266/3.0.2/libraries/ESP8266HTTPClient/src /private/var/folders/3t/s2qs3f713zvgvt7kq31rkrxc0000gn/T/arduino-sketch-61C39F221C08F1DF8BAEF1771E5B7836/sketch/anavi-thermometer-sw.ino.cpp -o /dev/null
Alternatives for DNSServer.h: [DNSServer@1.1.1]
ResolveLibrary(DNSServer.h)
  -> candidates: [DNSServer@1.1.1]
/Users/andypiper/Library/Arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/3.0.4-gcc10.3-1757bed/bin/xtensa-lx106-elf-g++ -D__ets__ -DICACHE_FLASH -U__STRICT_ANSI__ -D_GNU_SOURCE -I/Users/andypiper/Library/Arduino15/packages/esp8266/hardware/esp8266/3.0.2/tools/sdk/include -I/Users/andypiper/Library/Arduino15/packages/esp8266/hardware/esp8266/3.0.2/tools/sdk/lwip2/include -I/Users/andypiper/Library/Arduino15/packages/esp8266/hardware/esp8266/3.0.2/tools/sdk/libc/xtensa-lx106-elf/include -I/private/var/folders/3t/s2qs3f713zvgvt7kq31rkrxc0000gn/T/arduino-sketch-61C39F221C08F1DF8BAEF1771E5B7836/core -c -w -Werror=return-type -Os -g -free -fipa-pta -mlongcalls -mtext-section-literals -fno-rtti -falign-functions=4 -std=gnu++17 -ffunction-sections -fdata-sections -fno-exceptions -DMMU_IRAM_SIZE=0x8000 -DMMU_ICACHE_SIZE=0x8000 -w -x c++ -E -CC -DNONOSDK22x_190703=1 -DF_CPU=80000000L -DLWIP_OPEN_SRC -DTCP_MSS=536 -DLWIP_FEATURES=1 -DLWIP_IPV6=0 -DARDUINO=10607 -DARDUINO_ESP8266_GENERIC -DARDUINO_ARCH_ESP8266 "-DARDUINO_BOARD=\"ESP8266_GENERIC\"" -DLED_BUILTIN=2 -DFLASHMODE_DOUT -DESP8266 -I/Users/andypiper/Library/Arduino15/packages/esp8266/hardware/esp8266/3.0.2/cores/esp8266 -I/Users/andypiper/Library/Arduino15/packages/esp8266/hardware/esp8266/3.0.2/variants/generic -I/Users/andypiper/Library/Arduino15/packages/esp8266/hardware/esp8266/3.0.2/libraries/ESP8266WiFi/src -I/Users/andypiper/Library/Arduino15/packages/esp8266/hardware/esp8266/3.0.2/libraries/ESP8266httpUpdate/src -I/Users/andypiper/Library/Arduino15/packages/esp8266/hardware/esp8266/3.0.2/libraries/ESP8266HTTPClient/src -I/Users/andypiper/Library/Arduino15/packages/esp8266/hardware/esp8266/3.0.2/libraries/DNSServer/src /private/var/folders/3t/s2qs3f713zvgvt7kq31rkrxc0000gn/T/arduino-sketch-61C39F221C08F1DF8BAEF1771E5B7836/sketch/anavi-thermometer-sw.ino.cpp -o /dev/null
Alternatives for NTPClient.h: []
ResolveLibrary(NTPClient.h)
  -> candidates: []
Using library ESP8266WiFi at version 1.0 in folder: /Users/andypiper/Library/Arduino15/packages/esp8266/hardware/esp8266/3.0.2/libraries/ESP8266WiFi 
Using library ESP8266httpUpdate at version 1.3 in folder: /Users/andypiper/Library/Arduino15/packages/esp8266/hardware/esp8266/3.0.2/libraries/ESP8266httpUpdate 
Using library ESP8266HTTPClient at version 1.2 in folder: /Users/andypiper/Library/Arduino15/packages/esp8266/hardware/esp8266/3.0.2/libraries/ESP8266HTTPClient 
Using library DNSServer at version 1.1.1 in folder: /Users/andypiper/Library/Arduino15/packages/esp8266/hardware/esp8266/3.0.2/libraries/DNSServer 
Compilation error: Error: 13 INTERNAL: exit status 1
```

**Comment by leon-anavi** [comment]
Hi @andypiper,

Thank you for reporting this issue and sorry for the inconvenience. We'll need to investigate it.

As of the moment [chapter "Setting up the Arduino IDE" in the user's manual](https://github.com/AnaviTechnology/anavi-docs/blob/master/anavi-thermometer/anavi-thermometer.md#setting-up-the-arduino-ide) is for the older versions 1.8.x, for example 1.8.15.

Best regards,
Leon

**Comment by andypiper** [comment]
OK, I think this can be closed as invalid, actually.

I used Arduino 1.8.13 to compile, and that worked ok. Once I had done that, using 2.0 to compile worked as well. I think what must have happened is that I had not installed the correct libraries when I first tried in 2.0 (specifically it looks like I was missing NTPClient.h from the error above), and installing it in 1.8.13 meant that 2.0 picked it up as well since they are all stored in the same place. The error from the Arduino IDE was not very helpful first time around, but I think this is making sense, now.
